### ISSUE TITLE
v2-devにおいてインスタンス変数が利用できない

### ISSUE THREAD

**Issue by pyama86** [matsumotory/ngx_mruby#349]
```
mruby_init_worker_code '
  @redis = 'test'
';
```
上記のようなコードを書くと、下記の例外が発生する。

```
2018/05/07 19:11:43 [error] 12234#0: mrb_run failed. error: ArgumentError: cannot set instance variable
```

mrubyにおいて、Procオブジェクトにインスタンス変数を作成することは許容されていないので、発生するようです。

https://github.com/mruby/mruby/blob/master/src/variable.c#L280
https://github.com/mruby/mruby/blob/master/src/variable.c#L223

gdbの結果は下記のとおりです。

```
root@localhost:/home/pyama/src/github.com/matsumotory/ngx_mruby# gdb ./build/nginx/sbin/nginx 
(gdb) set follow-fork-mode child ★子プロセスもデバッグする
(gdb) b variable.c:280 ★例外が起きるところにブレーク
Breakpoint 1 at 0x42f508: file /home/pyama/src/github.com/matsumotory/ngx_mruby/mruby/src/variable.c, line 280.
(gdb) run ★実行する
Starting program: /home/pyama/src/github.com/matsumotory/ngx_mruby/build/nginx/sbin/nginx 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
"[31935] init master process"
"ngx_mruby: STREAM: mruby_stream_init_code"

Breakpoint 1, mrb_iv_set (mrb=mrb@entry=0xa26c20, v=..., sym=<optimized out>, obj=...) at /home/pyama/src/github.com/matsumotory/ngx_mruby/mruby/src/variable.c:280
280         mrb_raise(mrb, E_ARGUMENT_ERROR, "cannot set instance variable");
(gdb) bt ★バックトレースを見る
#0  mrb_iv_set (mrb=mrb@entry=0xa26c20, v=..., sym=<optimized out>, obj=...) at /home/pyama/src/github.com/matsumotory/ngx_mruby/mruby/src/variable.c:280
#1  0x0000000000574548 in mrb_iv_set (v=..., sym=<optimized out>, obj=..., mrb=0xa26c20) at /home/pyama/src/github.com/matsumotory/ngx_mruby/mruby/src/variable.c:423
#2  mrb_vm_iv_set (mrb=mrb@entry=0xa26c20, sym=<optimized out>, v=...) at /home/pyama/src/github.com/matsumotory/ngx_mruby/mruby/src/variable.c:422
#3  0x00000000005785b3 in mrb_vm_exec (mrb=mrb@entry=0xa26c20, proc=<optimized out>, proc@entry=0xa32820, pc=<optimized out>)
    at /home/pyama/src/github.com/matsumotory/ngx_mruby/mruby/src/vm.c:1117
#4  0x000000000057d21c in mrb_vm_run (mrb=0xa26c20, proc=0xa32820, self=..., stack_keep=<optimized out>)
    at /home/pyama/src/github.com/matsumotory/ngx_mruby/mruby/src/vm.c:935
#5  0x000000000057e3af in mrb_run (self=..., proc=0xa32820, mrb=0xa26c20) at /home/pyama/src/github.com/matsumotory/ngx_mruby/mruby/src/vm.c:2982
#6  mrb_funcall_with_block (mrb=mrb@entry=0xa26c20, self=..., mid=mid@entry=149, argc=<optimized out>, argc@entry=0, argv=argv@entry=0x7fffffffe060, blk=...)
    at /home/pyama/src/github.com/matsumotory/ngx_mruby/mruby/src/vm.c:493
#7  0x000000000057e7c0 in mrb_funcall_with_block (mrb=mrb@entry=0xa26c20, self=..., mid=149, argc=argc@entry=0, argv=argv@entry=0x7fffffffe060, blk=...)
    at /home/pyama/src/github.com/matsumotory/ngx_mruby/mruby/src/vm.c:398
#8  0x000000000057ec7c in mrb_funcall_argv (argv=0x7fffffffe060, argc=0, mid=<optimized out>, self=..., mrb=0xa26c20)
    at /home/pyama/src/github.com/matsumotory/ngx_mruby/mruby/src/vm.c:503
#9  mrb_funcall (mrb=0xa26c20, self=..., name=<optimized out>, argc=0) at /home/pyama/src/github.com/matsumotory/ngx_mruby/mruby/src/vm.c:383
#10 0x0000000000541aef in ngx_mrb_run_without_stop (mrb=0xa26c20, rproc=0xac3ab0, result=0x0)
    at /home/pyama/src/github.com/matsumotory/ngx_mruby/src/http/ngx_http_mruby_async.c:42
#11 0x00000000005341a4 in ngx_mrb_run_cycle (cycle=0xa0eed0, state=0xa12e70, code=0xb2fa00)
    at /home/pyama/src/github.com/matsumotory/ngx_mruby/src/http/ngx_http_mruby_module.c:733
#12 0x0000000000533cef in ngx_http_mruby_init_worker (cycle=0xa0eed0) at /home/pyama/src/github.com/matsumotory/ngx_mruby/src/http/ngx_http_mruby_module.c:614
#13 0x0000000000475be0 in ngx_single_process_cycle (cycle=0xa0eed0) at src/os/unix/ngx_process_cycle.c:300
#14 0x00000000004309d0 in main (argc=1, argv=0x7fffffffe658) at src/core/nginx.c:379
```

**Comment by pyama86** [comment]
リリースした。
