### ISSUE TITLE
SIGSEGV on v2-dev

### ISSUE THREAD

**Issue by yyamano** [matsumotory/ngx_mruby#357]
I get segfault with 4555acb690f1331663c5c39ef3a06a3186b11a44 (the latest commit on v2-dev branch). 

I don't have time to narrow down the problem and write simple code to reproduce it for now.
1b35861b27446ee6a465e98718785f462e2ccc43 works fine.

```
Program received signal SIGSEGV, Segmentation fault.
0x000000000049ce1c in ngx_http_mruby_set_handler (r=0x87e970, val=0x7fffffffde40, v=<optimized out>, data=0x983c18)
    at /home/vagrant/foo/ngx_mruby/src/http/ngx_http_mruby_module.c:1591
1591	  ctx->set_var_target = filter_data->target;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.6.x86_64 libgcc-4.8.5-4.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64 openssl-libs-1.0.1e-51.el7_2.5.x86_64 pcre-8.32-15.el7_2.1.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  0x000000000049ce1c in ngx_http_mruby_set_handler (r=0x87e970, val=0x7fffffffde40, v=<optimized out>, data=0x983c18)
    at /home/vagrant/foo/ngx_mruby/src/http/ngx_http_mruby_module.c:1591
#1  0x00000000004a4107 in ndk_set_var_multi_value_data_code (e=0x87f750)
    at /home/vagrant/foo/ngx_mruby/dependence/ngx_devel_kit/src/ndk_set_var.c:217
#2  0x00000000004886fd in ngx_http_rewrite_handler (r=0x87e970) at src/http/modules/ngx_http_rewrite_module.c:180
#3  0x0000000000451bf3 in ngx_http_core_rewrite_phase (r=0x87e970, ph=0xa3a3b8) at src/http/ngx_http_core_module.c:905
#4  0x000000000044dc63 in ngx_http_core_run_phases (r=r@entry=0x87e970) at src/http/ngx_http_core_module.c:851
#5  0x000000000044dd72 in ngx_http_handler (r=r@entry=0x87e970) at src/http/ngx_http_core_module.c:834
#6  0x0000000000455b52 in ngx_http_process_request (r=r@entry=0x87e970) at src/http/ngx_http_request.c:1948
#7  0x00000000004587f3 in ngx_http_process_request_headers (rev=rev@entry=0xa733d0) at src/http/ngx_http_request.c:1375
#8  0x0000000000458b09 in ngx_http_process_request_line (rev=rev@entry=0xa733d0) at src/http/ngx_http_request.c:1048
#9  0x0000000000459534 in ngx_http_wait_request_handler (rev=0xa733d0) at src/http/ngx_http_request.c:506
#10 0x000000000044a85e in ngx_epoll_process_events (cycle=0x86d9d0, timer=<optimized out>, flags=<optimized out>)
    at src/event/modules/ngx_epoll_module.c:902
#11 0x00000000004406f2 in ngx_process_events_and_timers (cycle=cycle@entry=0x86d9d0) at src/event/ngx_event.c:242
#12 0x00000000004498a0 in ngx_single_process_cycle (cycle=cycle@entry=0x86d9d0) at src/os/unix/ngx_process_cycle.c:310
#13 0x00000000004216c5 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:379
(gdb) p ctx
$1 = (ngx_http_mruby_ctx_t *) 0x0
(gdb) l
1586	  ngx_http_mruby_set_var_data_t *filter_data;
1587	  ngx_http_mruby_ctx_t *ctx = ngx_http_get_module_ctx(r, ngx_http_mruby_module);
1588	
1589	  filter_data = data;
1590	
1591	  ctx->set_var_target = filter_data->target;
1592	
1593	  if (filter_data->state == NGX_CONF_UNSET_PTR) {
1594	    return NGX_DECLINED;
1595	  }
```

**Comment by matsumotory** [comment]
@yyamano Thank you for your report. For now, could you tell us the nginx configuration and benchmark client settings?

**Comment by yyamano** [comment]
The code works fine with the latest version of v1 too. I developed it with v1.

**Comment by yyamano** [comment]
@pyama86 Thank you! It is fixed.
